name: Dry-Run Build
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 bandit
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Security Check
      run: |
        bandit -r src
    - name: Dry-Run
      run: |
        python src/datascraper.py "https://www.sports-reference.com/cbb/seasons/2022-school-stats.html"
    - name: Archive scraped data
      uses: actions/upload-artifact@v3
      with:
        name: NCAA-Game-Logs
        path: NCAA-Game-Logs.csv
        

